sudo: required
services:
  - docker

before_install:
  - docker build lototskyi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lototskyi/react-test npm test -- --coverage

after_success:
  - docker build -t olexandr1docker/multi-client ./client
  - docker build -t olexandr1docker/multi-nginx ./nginx
  - docker build -t olexandr1docker/multi-server ./server
  - docker build -t olexandr1docker/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push olexandr1docker/multi-client
  - docker push olexandr1docker/multi-nginx
  - docker push olexandr1docker/multi-server
  - docker push olexandr1docker/multi-worker